### ISSUE TITLE
initdb fails

### ISSUE THREAD

**Issue by swills** [repology/repology#427]
Trying to update my instance, I had to delete the database and re-create it, but initdb fails:

```
(venv) repology# ./repology-update.py --initdb

Jan 03 17:47:44 connecting to database
Jan 03 17:47:44   (re)initializing database schema
Traceback (most recent call last):
  File "./repology-update.py", line 194, in <module>
    os.sys.exit(Main())
  File "./repology-update.py", line 183, in Main
    ProcessDatabase(options=options, logger=logger, repoman=repoman, repositories_updated=repositories_updated)
  File "./repology-update.py", line 77, in ProcessDatabase
    database.CreateSchema()
  File "/repology/checkout/repology/database.py", line 573, in CreateSchema
    """)
psycopg2.ProgrammingError: syntax error at or near "GENERATED"
LINE 3:                 id integer GENERATED BY DEFAULT AS IDENTITY ...
```

Something I've done wrong or is this a bug?

**Comment by AMDmi3** [comment]
PostgreSQL 10 is required, may you be using older version?

**Comment by swills** [comment]
Ah, missed that, thanks for the hint. Sorry for the noise.
